package: 
  name: atlas
  version: "0.4.2"

source: 
  # This is the path to the source code (i.e., where the pyproject.toml is located)
  path: ../

requirements: 
  build: 
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host: 
    - python {{ python }}
    - pip 
    - pybind11
    - scikit-build-core>=0.3.3
    - numpy<=1.26
    - gdal           
    - opencv         

  run: 
    # Specifies the runtime dependencies
    - python>=3.9
    - pyyaml
    - gdal 
    - opencv 


about: 

  home: https://github.com/MicheleCeresoli/atlas  
  summary: "Ray Tracing Lunar DEM Images"
