name: Build Package 

on:  
  push: 
    tags:   
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs: 
  build-package: 
    runs-on: ${{matrix.os}}
    strategy:

      matrix: 
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
    
      - name: Setup Python 
        uses: actions/setup-python@v4
        with: 
          python-version: ${{matrix.python-version}}

      - name: Install build dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y libgdal-dev
          sudo apt-get install -y libopencv-dev
          
          python -m pip install --upgrade pip 
          python -m pip install build 

      - name: Build the wheel 
        run: python -m build --wheel

      - name: Archive the wheel 
        uses: actions/upload-artifact@v3 
        with: 
          name: wheel 
          path: dist/*.whl

      # Install Miniconda and set up the Conda environment with a specific Python version
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{matrix.python-version}}  
          channels: conda-forge

      - name: Install conda dependencies
        run: | 
          conda activate test
          conda install conda-build 

      - name: Build conda-package 
        run: | 
          conda build recipe
          CONDA_BUILD_FILE=$(conda build recipe --output)
          echo "CONDA_BUILD_PATH=$(dirname "$CONDA_BUILD_FILE")" >> $GITHUB_ENV

      - name: Archive the conda-package 
        uses: actions/upload-artifact@v3 
        with: 
          name: conda-packages
          path: ${{ env.CONDA_BUILD_PATH }}/*.tar.bz2


  upload-package: 
    needs: build-package 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Create release 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        with: 
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false 
          prerelease: false 
          
      - name: Download wheels 
        uses: actions/download-artifact@v3 
        with: 
          name: wheel 
          path: wheels 

      - name: Upload wheel to GitHub Release 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        run: | 
          for file in wheels/*whl; do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file"
          done

      - name: Download conda-packages 
        uses: actions/download-artifact@v3 
        with: 
          name: conda-packages 
          path: conda-packages 

      - name: Upload conda-package to GitHub Release 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        run: | 
          for file in conda-packages/*.tar.bz2; do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file"
          done