name: Build Conda Packages

on:
  push:
  # workflow_run:
    # workflows: ["Build Wheels"]
    # types:
      # - completed

jobs: 
  build-conda:
    runs-on: ${{matrix.os}}
    strategy: 

      matrix: 
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
    
      - name: Setup Python 
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path 
        run: | 
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies 
        run: | 
          conda install conda-build 

      - name: Build Conda Package 
        run: |         
          CONDA_BUILD_FILE=$(conda build recipe --output)
          echo "CONDA_BUILD_PATH=$(dirname "$CONDA_BUILD_FILE")" >> $GITHUB_ENV

      - name: Archive the Package 
        uses: actions/upload-artifact@v3 
        with: 
          name: conda-packages
          path: ${{ env.CONDA_BUILD_PATH }}


  upload-package: 
    needs: build-conda 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Download package 
        uses: actions/download-artifact@v3 
        with: 
          name: conda-packages 
          path: conda-packages

      - name: Upload package to GitHub Release 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        run: | 
          for file in conda-packages/*.tar.bz2; do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file"
          done