name: Build Wheels 

on:  
  push: 
    tags:   
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs: 
  build-wheels: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest]

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
    
      - name: Setup Python 
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'

      - name: Install build dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y libgdal-dev
          sudo apt-get install -y libopencv-dev
          
          python -m pip install --upgrade pip 
          python -m pip install build 

      - name: Build the wheel 
        run: python -m build --wheel

      - name: Archive the wheel 
        uses: actions/upload-artifact@v3 
        with: 
          name: wheel 
          path: dist/*.whl


  upload-wheels: 
    needs: build-wheels 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Download wheels 
        uses: actions/download-artifact@v3 
        with: 
          name: wheel 
          path: wheels 

      - name: Create release 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release v0.1.0
          draft: false 
          prerelease: false 

      - name: Upload wheel to GitHub Release 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ARCADIA }}
        run: | 
          for file in wheels/*whl; do
            echo "Uploading $file"
            gh release upload `Release v0.1.0` "$file"
          done